source /etc/makepkg.conf

CARCH="armv6h"
CHOST="armv6-rpi-linux-gnueabihf"

CFLAGS="-O2 -pipe -march=armv6zk -mtune=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard"
CXXFLAGS="${CFLAGS}"
LDFLAGS=""
CPPFLAGS=""

CC="armv6-rpi-linux-gnueabihf-gcc"
CXX="armv6-rpi-linux-gnueabihf-g++"
AR="armv6-rpi-linux-gnueabihf-ar"
RANLIB="armv6-rpi-linux-gnueabihf-ranlib"

STRIP="armv6-rpi-linux-gnueabihf-strip"

# CRITICAL: We must disable 'check' and ensure 'buildflags' doesn't overwrite our flags
BUILDENV=(!distcc !ccache !check !sign)
OPTIONS=(strip !docs !libtool !staticlibs emptydirs zipman purge !debug)
